# Generated by Django 4.0.5 on 2022-09-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massage',
            name='room',
            field=models.CharField(max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='massage',
            name='user',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='massage',
            name='value',
            field=models.CharField(max_length=100000, null=True),
        ),
    ]
